config/routes.rb
Rails.application.routes.draw do

  root "sessions#new"

  get 'new_session' => "sessions#new"
  post 'log_in'  => "sessions#create", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  resources :users do
    resources :transactions
    resources :groups, except: [:destroy] do
      resources :squaring_events, only: [:index, :new, :show, :create]
    end
    resources :squaring_events, only: [:index, :create, :new, :show]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :debits, :foreign_key => :creditor_id, :class_name => "Transaction"
  has_many :credits, :foreign_key => :debtor_id, :class_name => "Transaction"

  has_many :user_squarings
  has_many :squaring_events, :through => :user_squarings
  has_many :memberships
  has_many :groups, :through => :memberships

  has_secure_password

  def find_balance(transactions=nil)
    sum_debits(transactions) - sum_credits(transactions)
  end

  def sum_debits(transactions=nil)
    if transactions
      transactions.inject(0) do |sum, transaction|
        transaction.creditor_id == self.id ? transaction.amount + sum : sum
      end

    else
      self.debits.inject(0) do |sum, debit|
        (sum + debit.amount)
      end
    end
  end

  def sum_credits(transactions=nil)
    if transactions
      transactions.inject(0) do |sum, transaction|
        transaction.debtor_id == self.id ? transaction.amount + sum : sum
      end
    else
      self.credits.inject(0) do |sum, credit|
        (sum + credit.amount)
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	include UsersHelper

	def index
	end

#GET - render registration page
	def new
		@user = User.new
	end

#POST - create new user via registration page
	def create
		@user = User.new(user_params)
	  if @user.save
	  	session[:user_id] = @user.id
	  	redirect_to user_url(@user)
	  else
	  	flash.notice = "User Registration failed. Try again."
	  	render 'new'
	  end
	end

	def show
		@user = User.find(params[:id])
		@transactions = Transaction.where("debtor_id = ? OR creditor_id = ?", @user.id, @user.id).reverse_order
	end

end

app/helpers/users_helper.rb
module UsersHelper

	def user_params
	  params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
	end

end

app/views/users/new.html.erb
<!-- create new user -->
<div id="registration-content">
	<h3>Create New User:</h3>
	<div id="registration-form">
    <p>
    <%= form_for @user do |f| %>
      <%= f.label :first_name %>
      <%= f.text_field :first_name, placeholder: "first name" %><br/>

      <%= f.label :last_name %>
      <%= f.text_field :last_name, placeholder: "last name" %><br/>

      <%= f.label :email %>
      <%= f.text_field :email, placeholder: "email" %><br/>

      <%= f.label :password %>
      <%= f.password_field :password, placeholder: "create password" %><br/>

      <%= f.label :password %>
      <%= f.password_field :password_confirmation, placeholder: "confirm password" %><br/>

      <%= f.submit 'Register' %>
      <% end %>
  	</p>
	</div>
	<div id="send-to-registration">
	<%= link_to "cancel", root_path, id: "cancel-registration" %>
	</div>

</div>

app/views/users/show.html.erb
<!-- user profile page: shown after login -->
<div id="add-trans-link"><%= link_to "Add Transaction", new_user_transaction_path(@user) %></br></div>
<div id="create-square-up"><%= link_to "Create Square Up", "/users/#{@user.id}/groups", method: :post %></div>
<div id="profile-page-content">
	<h2>Welcome, <%= @user.first_name %> <%= @user.last_name %>.</h2>
	<h3>Transactions</h3>

  <div class group_transactions>
  <% @transactions.each do |transaction| %>
    <dl class="accordion" data-accordion>
      <dd class="accordion-navigation">
        <% if current_user == transaction.debtor %>
          <a href="#panel1">You owe <%= transaction.creditor.first_name %> <%= number_to_currency(transaction.amount) %> </a>
        <% else %>
          <a href="#panel1"><%= transaction.debtor.first_name %> owes You <%= number_to_currency(transaction.amount) %> </a>
        <% end %>
        <div id="panel1" class="content">
          <table>
            <thead>
              <tr>
                <th width="120">Borrower</th>
                <th width="120">Lender</th>
                <th width="80">Amount</th>
                <th width="200">Description</th>
                <th width="100">Status</th>
                <th width="100"></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= transaction.debtor.first_name %> <%= transaction.debtor.last_name %></td>
                <td><%= transaction.creditor.first_name %> <%= transaction.creditor.last_name %></td>
                <td><%= number_to_currency(transaction.amount) %></td>
                <td><%= transaction.description %></td>
                <% if transaction.closed == true %>
                	<td class="marked-paid">Paid</td>
                	<td></td>
                <% else %>
                	<td>Unpaid</td>
                	<td><%= link_to 'mark as paid', user_transaction_path(@user, transaction), method: :patch %></td>
                <% end %>
              </tr>
            </tbody>
          </table>
        </div>
      </dd>
    </dl>
  <% end %>
  </div>