config/routes.rb
Rails.application.routes.draw do

  root "sessions#new"

  get 'new_session' => "sessions#new"
  post 'log_in'  => "sessions#create", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"

  resources :users do
    resources :transactions
    resources :groups, except: [:destroy] do
      resources :squaring_events, only: [:index, :new, :show, :create]
    end
    resources :squaring_events, only: [:index, :create, :new, :show]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Mano-a-Many</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <% if session[:user_id] %>
            <h1><%= link_to "Mano | a | Many", user_path(current_user) %></h1>
          <% else %>
            <h1><a href="/">Mano | a | Many</a></h1>
          <% end %>
        </li>
        <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
        <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
      </ul>
      <% if session[:user_id] %>
      <div id="top-nav-bar">
        <%= link_to "logout", log_out_path %>
      </div>
      <% end %>
    </nav>

    <div class="panel row large-10 large-offset-2 columns">
      <p class="flash"><%= flash.notice %></p>
      <%= yield %>
    </div>
    <%= javascript_include_tag "application" %>
  </body>
</html>